[package]
name = "trellis"
version = "0.2.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-multipart = "0.7.2"
anyhow = "1.0"
confik = "0.15.1"
sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite", "macros"] }
actix-cors = "0.7.1"
serde_json = "1.0.140"
chrono = {version ="0.4.41", features = ["serde"]}
argon2 = "0.5.3"
serde = { version = "1.0.219", features = ["derive"] }
actix-ws = "0.4.0"
actix-files = "0.6.6"
env_logger = "0.11.8"
log = "0.4.27"
regex = "1.11.1"
reqwest = { version = "0.13.2", features = ["json"] }
futures-util = "0.3.31"
hex = "0.4.3"
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png", "webp"] }
ravif = "0.13.0"
sha2 = "0.11.0"
tokio = { version = "1.43", features = ["full"] }
actix-limitation = "0.5.1"
handlebars = "6.3.2"
notify = "8.2.0"
rushdown = "0.18.0"
rushdown-meta = "0.9.9"
walkdir = "2.5.0"
rushdown-highlighting = "0.9.8"
yaml-rust = "0.4.5"
rushdown-footnote = "0.9.8"
rushdown-diagram = "0.10.2"
